### PR TITLE
Remove file size check

### PR DESCRIPTION
**Pull request by cpeel**
If the file is small enough to be successfully uploaded (based on PHP configuration values) it should be small enough to run the tools against.

For TEST the max upload size is 48MB. For PROD it is 64MB.

### CODE REVIEW

**Comment by srjfoo** [comment]
Rarely, in the past, PPer uploads for PPV have exceeded the max upload size (whereupon we had to dance around the issue). Does the interface explicitly mention the max upload size, and document how it should be handled if the upload is too large?

**Comment by cpeel** [comment]
> Rarely, in the past, PPer uploads for PPV have exceeded the max upload size (whereupon we had to dance around the issue). Does the interface explicitly mention the max upload size, and document how it should be handled if the upload is too large?

It does not. Unfortunately each tool has its own upload form so there's no central place to add this (not that it would be hard to update all of the tools to include it.

Moreover, I don't know that we have a way to handle cases where the upload is too large. Presumably someone could upload a zip file via RFM and someone could run the desired tool against the file for them but that's not documented anywhere that I know of.

**Review by windymilla — APPROVED** [review]
I agree with the rationale and the code change

**Comment by srjfoo** [comment]
> > Rarely, in the past, PPer uploads for PPV have exceeded the max upload size (whereupon we had to dance around the issue). Does the interface explicitly mention the max upload size, and document how it should be handled if the upload is too large?
> 
> It does not. Unfortunately each tool has its own upload form so there's no central place to add this (not that it would be hard to update all of the tools to include it.
> 
> Moreover, I don't know that we have a way to handle cases where the upload is too large. Presumably someone could upload a zip file via RFM and someone could run the desired tool against the file for them but that's not documented anywhere that I know of.

I think I was thinking more in terms of a warning at the top of the ppwb home page in intro paragraph, documenting the max upload size (that would cover all of the tests).

And yes, I can see that trying to figure out a workaround for running a large file would be an issue.

**Comment by cpeel** [comment]
> I think I was thinking more in terms of a warning at the top of the ppwb home page in intro paragraph, documenting the max upload size (that would cover all of the tests).

That's a good compromise. I added a line to the home page that at least shows the maximum upload size.

**Pull request merged**
